name: TRADELINK_DEV

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: [self-hosted, tradelink-dev]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Create environment file
        run: |
          echo $'PORT=${{secrets.PORT}}\n' >> .env
          echo $'MONGODB_URI=${{secrets.MONGODB_URI}}\n' >> .env
          echo $'JWT_SECRET=${{secrets.JWT_SECRET}}\n' >> .env
      - name: Run docker compose
        run: |
          docker compose up -d --build
      - name: Clear unused containers
        run: |
          docker system prune -f
